"""
STANDMAP - Standards Recommendation Report & Procurement Specification Generator
Generates decision-support ReportLab PDF reports, interactive HTML reports, and draft tender clauses
for procurement officials and technical specification drafting.
"""

import os
from typing import Dict, Any, List
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_tender_clause_text(analysis: Dict[str, Any], recommendations: List[Dict[str, Any]], version_checks: List[Dict[str, Any]], cert_checks: List[Dict[str, Any]]) -> str:
    lines = []
    lines.append(f"### DRAFT TENDER CLAUSE: APPLICABLE INDIAN STANDARDS & CONFORMITY REQUIREMENTS")
    lines.append(f"**Tender Reference / Item:** {analysis.get('title', 'Procurement Item')}")
    lines.append(f"**Generated by:** STANDMAP Decision-Support Platform | Date: {datetime.now().strftime('%d-%b-%Y')}\n")
    lines.append("1. **RECOMMENDED APPLICABLE INDIAN STANDARDS (Subject to Authority Verification):**")
    lines.append("The supplied equipment/materials shall conform to the applicable editions of the following Indian Standards:")
    
    seen_stds = set()
    for rec in recommendations:
        std_id = rec["standard_id"]
        if std_id in seen_stds:
            continue
        seen_stds.add(std_id)
        is_num = rec.get("is_number", std_id)
        title = rec.get("standard_title", "")
        app_stat = rec.get("applicability_status", "APPLICABLE")
        lines.append(f"- **{is_num}**: *{title}* (Status: {app_stat})")

    lines.append("\n2. **NORMATIVE & ALLIED TEST METHOD STANDARDS:**")
    for rec in recommendations[:3]:
        relationships = rec.get("relationships", [])
        for rel in relationships:
            lines.append(f"- **{rel.get('target_is')}** ({rel.get('relationship_type')}): {rel.get('target_title')} — {rel.get('description', '')}")

    if version_checks:
        lines.append("\n3. **VERSION & AMENDMENT NOTICES:**")
        for vc in version_checks:
            lines.append(f"- {vc.get('warning_message')}")

    if cert_checks:
        lines.append("\n4. **MANDATORY CERTIFICATION & QUALITY CONTROL ORDERS (QCO):**")
        for cc in cert_checks:
            lines.append(f"- **{cc.get('mandate_level')}**: {cc.get('reason')}")

    lines.append("\n5. **GENERAL COMPLIANCE NOTE:**")
    lines.append("Bidders must provide valid BIS License copies, ISI Mark certificates, and type test certificates from NABL accredited laboratories during technical bid submission.")
    
    return "\n".join(lines)

def generate_html_report(analysis: Dict[str, Any], requirements: List[Dict[str, Any]], recommendations: List[Dict[str, Any]], version_checks: List[Dict[str, Any]], cert_checks: List[Dict[str, Any]], coverage: Dict[str, Any], reviews: List[Dict[str, Any]]) -> str:
    total_reqs = len(requirements)
    cov_pct = coverage.get("coverage_percentage", 0.0) if coverage else 0.0
    covered_cnt = coverage.get("covered_count", 0) if coverage else 0
    gaps_cnt = len(coverage.get("gaps_summary", [])) if coverage else 0
    outdated_cnt = sum(1 for v in version_checks if v.get("status") == "OUTDATED")

    req_rows = ""
    for r in requirements:
        badge = {
            "COVERED": "<span class='px-2 py-0.5 bg-emerald-100 text-emerald-800 rounded font-bold text-xs'>COVERED</span>",
            "PARTIAL": "<span class='px-2 py-0.5 bg-amber-100 text-amber-800 rounded font-bold text-xs'>PARTIAL</span>",
            "REVIEW": "<span class='px-2 py-0.5 bg-indigo-100 text-indigo-800 rounded font-bold text-xs'>REVIEW</span>",
            "NO_MATCH": "<span class='px-2 py-0.5 bg-rose-100 text-rose-800 rounded font-bold text-xs'>NO MATCH</span>"
        }.get(r.get("coverage_status"), "<span class='px-2 py-0.5 bg-gray-100 text-gray-800 rounded font-bold text-xs'>PENDING</span>")

        req_rows += f"""
        <tr class="border-b border-gray-200 hover:bg-gray-50 text-sm">
            <td class="py-3 px-4 font-mono text-xs font-bold text-gray-600">{r.get('id')}</td>
            <td class="py-3 px-4 font-bold text-xs text-blue-700 uppercase">{r.get('category')}</td>
            <td class="py-3 px-4 font-medium text-gray-900">{r.get('text')}</td>
            <td class="py-3 px-4 text-xs text-gray-500 font-mono">Page {r.get('source_page', 1)}<br><span class="text-gray-400">{r.get('source_section', '')}</span></td>
            <td class="py-3 px-4">{badge}</td>
        </tr>
        """

    rec_cards = ""
    seen_stds = set()
    for rec in recommendations:
        std_id = rec["standard_id"]
        if std_id in seen_stds:
            continue
        seen_stds.add(std_id)
        
        is_num = rec.get("is_number", std_id)
        title = rec.get("standard_title", "")
        domain = rec.get("domain", "")
        scheme = rec.get("certification_scheme", "Voluntary Standard")
        match_reason = rec.get("match_reason", "")
        app_reason = rec.get("applicability_reason", "")
        
        relationships = rec.get("relationships", [])
        rel_html = ""
        for rel in relationships:
            rel_html += f"""
            <li class="text-xs text-gray-700 mt-1">
                <span class="font-bold text-indigo-700">[{rel.get('relationship_type')}]</span> 
                <strong>{rel.get('target_is')}</strong>: {rel.get('target_title')}
            </li>
            """
            
        rec_cards += f"""
        <div class="bg-white border border-gray-200 rounded-xl p-5 shadow-sm mb-4">
            <div class="flex justify-between items-start">
                <div>
                    <span class="bg-blue-100 text-blue-800 text-xs font-bold px-2.5 py-0.5 rounded font-mono">{is_num}</span>
                    <span class="ml-2 text-xs text-gray-500 font-medium">{domain}</span>
                    <h3 class="text-base font-bold text-gray-900 mt-1">{title}</h3>
                </div>
                <span class="bg-emerald-50 text-emerald-700 text-xs font-bold px-2.5 py-1 rounded border border-emerald-200">
                    {rec.get('applicability_status', 'APPLICABLE')}
                </span>
            </div>
            <div class="mt-3 text-xs text-gray-600 bg-gray-50 p-3 rounded-lg border border-gray-100">
                <p><strong>Match Justification:</strong> {match_reason}</p>
                <p class="mt-1"><strong>Applicability Reasoning:</strong> {app_reason}</p>
                <p class="mt-1"><strong>Certification Scheme:</strong> {scheme}</p>
            </div>
            {f'''<div class="mt-3">
                <h4 class="text-xs font-bold text-gray-700 uppercase tracking-wider">Normative & Allied Standards:</h4>
                <ul class="list-disc list-inside mt-1">{rel_html}</ul>
            </div>''' if rel_html else ''}
        </div>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>STANDMAP Standards Recommendation Report - {analysis.get('id')}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-100 p-8 font-sans antialiased text-slate-800">
    <div class="max-w-5xl mx-auto bg-white shadow-2xl rounded-2xl border border-slate-200 overflow-hidden">
        <!-- Header Banner -->
        <div class="bg-slate-900 text-white p-6 flex justify-between items-center">
            <div>
                <div class="flex items-center gap-2">
                    <span class="bg-blue-600 text-xs px-2.5 py-0.5 rounded font-bold uppercase tracking-wider">STANDMAP Decision Support</span>
                    <span class="text-slate-400 text-xs font-mono">{datetime.now().strftime('%d-%b-%Y %H:%M')}</span>
                </div>
                <h1 class="text-2xl font-black mt-1">Standards Recommendation & Specification Mapping Report</h1>
                <p class="text-sm text-slate-300">Department of Consumer Affairs • Smart Automation for Public Procurement</p>
            </div>
            <div class="text-right">
                <div class="text-xs text-slate-400 uppercase tracking-wider">Report ID</div>
                <div class="text-2xl font-mono font-bold text-blue-400">{analysis.get('id')}</div>
            </div>
        </div>

        <!-- Metadata Strip -->
        <div class="p-6 bg-slate-50 border-b border-gray-200 grid grid-cols-2 sm:grid-cols-4 gap-4 text-sm">
            <div>
                <div class="text-xs text-gray-500 font-medium uppercase">Specification Title</div>
                <div class="font-bold text-gray-800">{analysis.get('title')}</div>
            </div>
            <div>
                <div class="text-xs text-gray-500 font-medium uppercase">Procuring Organization</div>
                <div class="font-bold text-gray-800">{analysis.get('organization')}</div>
            </div>
            <div>
                <div class="text-xs text-gray-500 font-medium uppercase">Domain Category</div>
                <div class="font-bold text-blue-700">{analysis.get('category')}</div>
            </div>
            <div>
                <div class="text-xs text-gray-500 font-medium uppercase">Specification Coverage</div>
                <div class="font-bold text-emerald-700">{cov_pct}% Completed</div>
            </div>
        </div>

        <!-- KPI Strip -->
        <div class="p-6 border-b border-gray-200 grid grid-cols-4 gap-4">
            <div class="bg-blue-50 border border-blue-200 p-4 rounded-xl text-center">
                <div class="text-2xl font-black text-blue-700">{total_reqs}</div>
                <div class="text-xs font-bold text-blue-800 uppercase mt-1">Requirements Parsed</div>
            </div>
            <div class="bg-emerald-50 border border-emerald-200 p-4 rounded-xl text-center">
                <div class="text-2xl font-black text-emerald-700">{covered_cnt}</div>
                <div class="text-xs font-bold text-emerald-800 uppercase mt-1">Covered by Standards</div>
            </div>
            <div class="bg-amber-50 border border-amber-200 p-4 rounded-xl text-center">
                <div class="text-2xl font-black text-amber-700">{gaps_cnt}</div>
                <div class="text-xs font-bold text-amber-800 uppercase mt-1">Gaps / Review Cases</div>
            </div>
            <div class="bg-rose-50 border border-rose-200 p-4 rounded-xl text-center">
                <div class="text-2xl font-black text-rose-700">{outdated_cnt}</div>
                <div class="text-xs font-bold text-rose-800 uppercase mt-1">Outdated References</div>
            </div>
        </div>

        <!-- Section 1: Recommended Standards -->
        <div class="p-6 border-b border-gray-200">
            <h2 class="text-lg font-bold text-gray-900 mb-4 flex items-center justify-between">
                <span>1. Recommended Indian Standards & Allied Test Methods</span>
                <span class="text-xs font-normal text-gray-500">Source: Bureau of Indian Standards (BIS)</span>
            </h2>
            {rec_cards}
        </div>

        <!-- Section 2: Requirement Trace Matrix -->
        <div class="p-6">
            <h2 class="text-lg font-bold text-gray-900 mb-4">2. Source-Grounded Requirement Breakdown</h2>
            <div class="overflow-x-auto">
                <table class="w-full text-left border-collapse">
                    <thead>
                        <tr class="bg-slate-100 text-slate-700 uppercase font-semibold text-xs border-b border-gray-300">
                            <th class="py-3 px-4">Req ID</th>
                            <th class="py-3 px-4">Category</th>
                            <th class="py-3 px-4">Extracted Requirement</th>
                            <th class="py-3 px-4">Source Provenance</th>
                            <th class="py-3 px-4">Coverage</th>
                        </tr>
                    </thead>
                    <tbody>
                        {req_rows}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Footer -->
        <div class="p-6 bg-slate-50 border-t border-gray-200 flex justify-between items-center text-xs text-gray-500">
            <div>
                STANDMAP Decision-Support Platform • SIH26108 Prototype.<br>
                <em>"From procurement specification to a traceable standards map."</em>
            </div>
            <div class="text-right border-t-2 border-gray-400 pt-2 w-48">
                <div class="font-bold text-gray-800">Procurement Officer</div>
                <div>Technical Evaluation Sign-off</div>
            </div>
        </div>
    </div>
</body>
</html>"""

def generate_pdf_report(analysis: Dict[str, Any], requirements: List[Dict[str, Any]], recommendations: List[Dict[str, Any]], version_checks: List[Dict[str, Any]], cert_checks: List[Dict[str, Any]], output_path: str):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []
    
    title_style = ParagraphStyle(name='TitleStyle', parent=styles['Heading1'], fontSize=15, leading=18, textColor=colors.HexColor('#0f172a'))
    story.append(Paragraph(f"<b>STANDMAP Standards Recommendation Report</b>", title_style))
    story.append(Paragraph(f"Analysis ID: {analysis.get('id')} | Specification: {analysis.get('title')}", styles['Normal']))
    story.append(Paragraph(f"Organization: {analysis.get('organization')} | Category: {analysis.get('category')} | Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#2563eb'), spaceBefore=2, spaceAfter=10))
    
    # Table of Recommendations
    story.append(Paragraph("<b>1. Recommended Indian Standards:</b>", styles['Heading3']))
    data = [["IS Number", "Standard Title", "Domain", "Applicability", "Certification Status"]]
    seen = set()
    for rec in recommendations:
        std_id = rec["standard_id"]
        if std_id in seen:
            continue
        seen.add(std_id)
        data.append([
            rec.get("is_number", std_id),
            rec.get("standard_title", "")[:35],
            rec.get("domain", "")[:25],
            rec.get("applicability_status", "APPLICABLE"),
            rec.get("certification_status", "VOLUNTARY")
        ])
        
    t = Table(data, colWidths=[80, 160, 120, 80, 95])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8.5),
        ('BOTTOMPADDING', (0,0), (-1,0), 5),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('FONTSIZE', (0,1), (-1,-1), 7.5),
    ]))
    story.append(t)
    story.append(Spacer(1, 14))

    # Version Warnings
    if version_checks:
        story.append(Paragraph("<b>2. Version & Amendment Findings:</b>", styles['Heading3']))
        for vc in version_checks:
            v_color = '#dc2626' if vc.get('status') == 'OUTDATED' else '#2563eb'
            story.append(Paragraph(f"<font color='{v_color}'>• <b>{vc.get('status')}</b>: {vc.get('warning_message')}</font>", styles['Normal']))
            story.append(Spacer(1, 4))
        story.append(Spacer(1, 10))

    # Certification Findings
    if cert_checks:
        story.append(Paragraph("<b>3. Statutory Certification & QCO Mandates:</b>", styles['Heading3']))
        for cc in cert_checks:
            story.append(Paragraph(f"• <b>{cc.get('mandate_level')}</b>: {cc.get('reason')}", styles['Normal']))
            story.append(Spacer(1, 4))
        story.append(Spacer(1, 10))

    story.append(Spacer(1, 10))
    story.append(Paragraph("<i>This decision-support report is generated by STANDMAP based on public BIS catalogue metadata. Procuring officials should verify final requirements against authoritative gazette notifications.</i>", styles['Italic']))
    
    doc.build(story)
    return output_path
